# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mechanics puzzles
email: sandor@mysteryleague.com
description: > # this means to ignore newlines until "baseurl:"
  Mechnaics puzzles for Nova to Lodestar
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nova-to-lodestar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: santheo
github_username:  santheo

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  low:
    output: true
    title: Low
    permalink: /:collection/:path/index.html
  med:
    output: true
    title: Medium
    permalink: /:collection/:path/index.html
  high:
    output: true
    title: High
    permalink: /:collection/:path/index.html

  red:
    output: true
    title: Red
    permalink: /:collection/:path/index.html
  blue:
    output: true
    title: Blue
    permalink: /:collection/:path/index.html
  yellow:
    output: true
    title: Yellow
    permalink: /:collection/:path/index.html

  red_yellow:
    output: true
    title: Red and Yellow
    permalink: /:collection/:path/index.html
  blue_red:
    output: true
    title: Blue and Red
    permalink: /:collection/:path/index.html
  yellow_blue:
    output: true
    title: Yellow and Blue
    permalink: /:collection/:path/index.html

  secondaries:
    output: true
    title: Secondaries
    permalink: /:collection/:path/index.html
  white:
    output: true
    title: White
    permalink: /:collection/:path/index.html
